### ISSUE TITLE
Failed to start on Unraid

### ISSUE THREAD

**Issue by PrintsLeo** [youroldmangaming/MeshSense#1]
Attempting to install the docker on Unraid.  Everything installed as expected, but the docker won't start.  I get the following information in my logs.

"#" node[1]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:68
"#" Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))

----- Native stack trace -----

1: 0xfeb747 node::Assert(node::AssertionInfo const&) [node]
2: 0x107f896 node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int) [node]
3: 0x107fa62 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
4: 0xf933a3 [node]
5: 0xf9549c node::Start(int, char**) [node]
6: 0x14ff11e6f24a [/lib/x86_64-linux-gnu/libc.so.6]
7: 0x14ff11e6f305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
8: 0xed009e _start [node]

**Comment by PrintsLeo** [comment]
I was able to get it to start by enabling "Privileged"

**Comment by youroldmangaming** [comment]
Hi 
Yes the run.sh had/has privileged mode set.

I have now also included it in the docker-compose.

**Comment by youroldmangaming** [comment]
docker run --rm -v ./data:/root/.local/share/meshsense/ -v ./dbus/:/var/run/dbus/system_bus_socket:ro -p 5920:5920 y0mg/meshsense:amd64

Use these settings  when you set it up in unraid also make sure you select previlleged. I got it working on a friends unraid setup today.

**Comment by youroldmangaming** [comment]
Closed - Multiple People now have it working on Unraid.

**Comment by PrintsLeo** [comment]
It's working great!  Thanks for your hard work!

**Comment by youroldmangaming** [comment]
All good glad to have saved other the pain doing it again.

**Comment by youroldmangaming** [comment]
Done
